[GLOBAL]
pants_version = "2.29.0"
backend_packages = [
    "pants.backend.shell",
]

[anonymous-telemetry]
enabled = false

[system-binaries]
system_binary_paths = [
  "/usr/bin",
  "/bin",
  "/usr/local/bin",
  "/opt/homebrew/bin",
  "/home/*/.nvm/versions/node/*/bin",
  "/Users/*/.nvm/versions/node/*/bin",
]

[cli.alias]
all = "::"

[source]
root_patterns = [
  "/",
]

[python]
interpreter_constraints = [">=3.12"]
